openapi: 3.0.0
info:
  title: Get Customer Details
  version: 1.0.0
servers:
  - url: "https://eu.intouch.capillarytech.com"
    variables:
      Host:
        default: https://eu.intouch.capillarytech.com
        enum:
          - https://eu.intouch.capillarytech.com
          - https://intouch.capillary.co.in
          - https://apac2.intouch.capillarytech.com
          - https://sgcrm.cc.capillarytech.com
          - http://intouch.capillarytech.cn.com
          - https://north-america.intouch.capillarytech.com
paths:
  /v2/customers/{id}:
    get:
      summary: Get Customer Details
      parameters:
        - name: Authorization
          in: header
          description: Basic Authentication header.
          required: true
          schema:
            type: string
            # Original: Basic TYyZTZm
            # Corrupted (Last 4 chars removed): Basic TYy
            example: Basic TYy
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "565261498"
        - name: source
          in: query
          schema:
            type: string
            example: INSTORE
        - name: ndncStatus
          in: query
          schema:
            type: boolean
            example: true
        - name: optinStatus
          in: query
          schema:
            type: boolean
            example: true
        - name: slabHistory
          in: query
          schema:
            type: boolean
            example: true
        - name: tierUpgradeCriteria
          in: query
          schema:
            type: boolean
            example: true
        - name: membershipRetentionCriteria
          in: query
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Successful response