openapi: 3.1.0
info:
  title: Earn Cart Promotion
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/promotions/{promotionId}/earn:
    post:
      summary: Earn Cart Promotion
      description: Description :With this API , we can get the details of all the cart promotions earned
        by a particular customer.
      operationId: earn-promotion
      parameters:
      - name: promotionId
        in: path
        description: The Unique promotion id
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Unique id assigned to the earn event
                customerId:
                  type: string
                  description: Unique id assigned to the customer
                promotionId:
                  type: string
                  description: Unique id assigned to the promotion
                earnedFromType:
                  type: string
                  description: 'Type of customer activity for which promotion is earned . Enums: ACTIVITY,MILESTONE,
                    REWARD'
                earnedFromId:
                  type: string
                  description: earn event id
                eventTime:
                  type: string
                  description: The time stamp
                  format: date-time
                validTill:
                  type: string
                  description: Validity of the earn
                  format: date
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data:
                      id: string
                      customerId: 0
                      promotionId: string
                      earnedFromType: ''
                      earnedFromId: string
                      eventTime: 0
                      eventDetails:
                        id: string
                        type: string
                        eventPayload:
                          additionalProp1: {}
                          additionalProp2: {}
                          additionalProp3: {}
                      validTill: 0
                      errorDetails:
                        errorCode: 0
                        errorMessages: string
                    errors:
                    - code: 0
                      message: string
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: string
                      customerId:
                        type: integer
                        example: 0
                        default: 0
                      promotionId:
                        type: string
                        example: string
                      earnedFromType:
                        type: string
                        example: ''
                      earnedFromId:
                        type: string
                        example: string
                      eventTime:
                        type: integer
                        example: 0
                        default: 0
                      eventDetails:
                        type: object
                        properties:
                          id:
                            type: string
                            example: string
                          type:
                            type: string
                            example: string
                          eventPayload:
                            type: object
                            properties:
                              additionalProp1:
                                type: object
                                properties: {}
                              additionalProp2:
                                type: object
                                properties: {}
                              additionalProp3:
                                type: object
                                properties: {}
                      validTill:
                        type: integer
                        example: 0
                        default: 0
                      errorDetails:
                        type: object
                        properties:
                          errorCode:
                            type: integer
                            example: 0
                            default: 0
                          errorMessages:
                            type: string
                            example: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 0
                          default: 0
                        message:
                          type: string
                          example: string
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/promotions/68f869d94a314550c4b46047/earn' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic Z2VvcmdlLmRW86NjVhMDgzYjk1MWY5MGY1NTY5NDk1YmNkNzUxYmJiY2U=' \
            --header 'Cookie: _cfuvid=BNm80w7q.f9c3OmoXlPgRUsybHmAv_l_3VQCTg-1772103718132-0.0.1.1-604800000' \
            --data '{
              "customerId": 566881933,
              "earnedFromType": "ACTIVITY",
              "earnedFromId": "TXN_12345_ABC",
              "eventTime": 1761748253000,
              "eventDetails": {
                "id": "TXN_12345_ABC",
                "type": "TransactionAdd",
                "eventPayload": {
                  "storeId": 101,
                  "amount": 75.50
                }
              }
            }'
          language: json
          name: ''
        samples-languages:
        - json
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
