openapi: 3.1.0
info:
  title: Get fulfillment status
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/fulfillmentStatus:
    get:
      summary: Get fulfillment status
      description: ''
      operationId: get-fulfillment-status
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                  - id: 164
                    orgId: 100737
                    name: DELIVERED
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
                  - id: 163
                    orgId: 100737
                    name: DELIVERING SOON
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
                  - id: 252
                    orgId: 100737
                    name: it is here
                    isEnabled: true
                    createdBy: 75155282
                    createdOn: 1741934183000
                    createdOnDateTime: '2025-03-14T06:36:23Z'
                    lastUpdatedBy: 75155282
                    lastUpdatedOn: 1741934183000
                    lastUpdatedOnDateTime: '2025-03-14T06:36:23Z'
                  - id: 253
                    orgId: 100737
                    name: it is here now
                    isEnabled: true
                    createdBy: 75155282
                    createdOn: 1741934783000
                    createdOnDateTime: '2025-03-14T06:46:23Z'
                    lastUpdatedBy: 75155282
                    lastUpdatedOn: 1741934783000
                    lastUpdatedOnDateTime: '2025-03-14T06:46:23Z'
                  - id: 162
                    orgId: 100737
                    name: ON ITS WAY
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
                With sortBy=lastUpdatedOn:
                  value:
                  - id: 253
                    orgId: 100737
                    name: DELIVERED2
                    isEnabled: true
                    createdBy: 75155282
                    createdOn: 1741934783000
                    createdOnDateTime: '2025-03-14T06:46:23Z'
                    lastUpdatedBy: 75155282
                    lastUpdatedOn: 1741934783000
                    lastUpdatedOnDateTime: '2025-03-14T06:46:23Z'
                  - id: 252
                    orgId: 100737
                    name: DELIVERED1
                    isEnabled: true
                    createdBy: 75155282
                    createdOn: 1741934183000
                    createdOnDateTime: '2025-03-14T06:36:23Z'
                    lastUpdatedBy: 75155282
                    lastUpdatedOn: 1741934183000
                    lastUpdatedOnDateTime: '2025-03-14T06:36:23Z'
                  - id: 164
                    orgId: 100737
                    name: DELIVERED
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
                  - id: 163
                    orgId: 100737
                    name: DELIVERING SOON
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
                  - id: 162
                    orgId: 100737
                    name: ON ITS WAY
                    isEnabled: true
                    createdBy: 75154383
                    createdOn: 1736405355000
                    createdOnDateTime: '2025-01-09T06:49:15Z'
                    lastUpdatedBy: 75154383
                    lastUpdatedOn: 1736405355000
                    lastUpdatedOnDateTime: '2025-01-09T06:49:15Z'
              schema:
                oneOf:
                - type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 164
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      name:
                        type: string
                        example: DELIVERED
                      isEnabled:
                        type: boolean
                        example: true
                        default: true
                      createdBy:
                        type: integer
                        example: 75154383
                        default: 0
                      createdOn:
                        type: integer
                        example: 1736405355000
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-01-09T06:49:15Z'
                      lastUpdatedBy:
                        type: integer
                        example: 75154383
                        default: 0
                      lastUpdatedOn:
                        type: integer
                        example: 1736405355000
                        default: 0
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-01-09T06:49:15Z'
                - title: With sortBy=lastUpdatedOn
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 253
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      name:
                        type: string
                        example: DELIVERED2
                      isEnabled:
                        type: boolean
                        example: true
                        default: true
                      createdBy:
                        type: integer
                        example: 75155282
                        default: 0
                      createdOn:
                        type: integer
                        example: 1741934783000
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-03-14T06:46:23Z'
                      lastUpdatedBy:
                        type: integer
                        example: 75155282
                        default: 0
                      lastUpdatedOn:
                        type: integer
                        example: 1741934783000
                        default: 0
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-03-14T06:46:23Z'
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/fulfillmentStatus' \
            --header 'Authorization: Basic aWFtc2hpdmFhbnjknVNKJFVblahDBLAHhlMzRkNWI1YTI5MWY=' \
            --header 'Cookie: _cfuvid=YLWKW2g3iSh26hCX0XcFCuh8oQRtUpC5dGAfoYq7hh0-1721653557209-0.0.1.1-604800000'
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/fulfillmentStatus?orderBy=DESC&sortBy=lastUpdatedOn' \
            --header 'Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg=' \
            --header 'Cookie: _cfuvid=YLWKW2g3iSh26hCX0XcFCuh8oQRtUpC5dGAfoYq7hh0-1721653557209-0.0.1.1-604800000; _cfuvid=0HswOUeY1hLB1ChixiPHPvEBpkBYBw.OmrLWQyfiBZ0-1747382714367-0.0.1.1-604800000'
          name: With sortBy=lastUpdatedOn
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
