openapi: 3.1.0
info:
  title: Get available brand rewards
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/reward/brand/{brandId}/available:
    get:
      summary: Get available brand rewards
      description: ''
      operationId: get-available-brand-rewards
      parameters:
      - name: brandId
        in: path
        description: Unique identifier of the brand.
        schema:
          type: integer
          format: int64
        required: true
      - name: startDate
        in: query
        required: true
        schema:
          type: string
        description: 'Start date in ISO 8601 format: YYYY-MM-DDTHH:MMZ (e.g. 2024-01-15T10:30Z)'
      - name: endDate
        in: query
        required: true
        schema:
          type: string
        description: 'End date in ISO 8601 format: YYYY-MM-DDTHH:MMZ (e.g. 2024-01-31T23:59Z)'
      - name: language
        in: query
        description: Filters the response based on the reward language. Use this parameter to retrieve
          rewards in a specific language. For example, to display rewards in English, set the parameter
          to en
        schema:
          type: string
          enum:
          - ''
          default: en
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status:
                      success: true
                      code: 6101
                      message: Reward details fetched successfully
                    rewardList:
                    - id: 4
                      name: 10% off on clothing
                      status: ENDED
                      startTime: '2021-05-10 18:45:14'
                      endTime: '2021-05-10 18:45:14'
                      type: VOUCHER
                      priority: 1
                      enabled: false
                      intouchPoints: 100
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs: null
                    - id: 7
                      name: 15% off on Skinny Jeans
                      status: ENDED
                      startTime: '2021-05-10 18:50:08'
                      endTime: '2021-05-10 18:50:08'
                      type: VOUCHER
                      priority: 2
                      enabled: false
                      intouchPoints: 200
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs: null
                    - id: 8
                      name: 200 off on shirts
                      status: ENDED
                      startTime: '2021-05-10 18:54:18'
                      endTime: '2021-05-10 18:54:18'
                      type: VOUCHER
                      priority: 3
                      enabled: false
                      intouchPoints: 500
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs: null
                    - id: 9
                      name: Flat 50% off on shoes
                      status: ENDED
                      startTime: '2021-05-10 19:13:16'
                      endTime: '2021-05-10 19:13:16'
                      type: VOUCHER
                      priority: 4
                      enabled: false
                      intouchPoints: 300
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs: null
                    - id: 206280
                      name: Eggo
                      status: ENDED
                      startTime: '2024-07-26 16:15:00'
                      endTime: '2024-07-26 16:15:00'
                      type: VOUCHER
                      priority: 1
                      enabled: true
                      intouchPoints: 0
                      redemptionType: INTOUCH_REWARD
                      groups:
                      - groupName: Kellanova Rewards
                        groupRank: null
                      rewardRank: 5
                      customFields: {}
                      paymentConfigs:
                      - paymentMode: FREE
                        id: 336
                    - id: 206281
                      name: Poptarts
                      status: ENDED
                      startTime: '2024-07-26 16:15:00'
                      endTime: '2024-07-26 16:15:00'
                      type: VOUCHER
                      priority: 1
                      enabled: true
                      intouchPoints: 0
                      redemptionType: INTOUCH_REWARD
                      groups:
                      - groupName: Kellanova Rewards
                        groupRank: null
                      rewardRank: 1
                      customFields: {}
                      paymentConfigs:
                      - paymentMode: FREE
                        id: 337
                    - id: 206609
                      name: testreward1
                      status: LIVE
                      startTime: '2024-07-26 07:38:00'
                      endTime: '2024-07-26 07:38:00'
                      type: VOUCHER
                      priority: 1
                      enabled: true
                      intouchPoints: 500
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: 1
                      customFields: {}
                      paymentConfigs:
                      - paymentMode: POINTS
                        id: 344
                        points: 100.0
                    - id: 206610
                      name: $10 cash back reward
                      status: LIVE
                      startTime: '2024-07-26 07:38:00'
                      endTime: '2024-07-26 07:38:00'
                      type: VOUCHER
                      priority: 1
                      enabled: true
                      intouchPoints: 1000
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs:
                      - paymentMode: POINTS
                        id: 345
                        points: 100.0
                    - id: 206610
                      name: $10 Nordstrom Notes
                      status: LIVE
                      startTime: '2024-07-26 07:38:00'
                      endTime: '2024-07-26 07:38:00'
                      type: VOUCHER
                      priority: 1
                      enabled: true
                      intouchPoints: 1000
                      redemptionType: INTOUCH_REWARD
                      groups: []
                      rewardRank: null
                      customFields: {}
                      paymentConfigs:
                      - paymentMode: POINTS
                        id: 345
                        points: 100.0
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 6101
                        default: 0
                      message:
                        type: string
                        example: Reward details fetched successfully
                  rewardList:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                          default: 0
                        name:
                          type: string
                          example: 10% off on clothing
                        status:
                          type: string
                          example: ENDED
                        startTime:
                          type: string
                          example: '2021-05-10 18:45:14'
                        endTime:
                          type: string
                          example: '2021-05-10 18:45:14'
                        type:
                          type: string
                          example: VOUCHER
                        priority:
                          type: integer
                          example: 1
                          default: 0
                        enabled:
                          type: boolean
                          example: false
                          default: true
                        intouchPoints:
                          type: integer
                          example: 100
                          default: 0
                        redemptionType:
                          type: string
                          example: INTOUCH_REWARD
                        groups:
                          type: array
                        rewardRank: {}
                        customFields:
                          type: object
                          properties: {}
                        paymentConfigs: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status:
                      success: false
                      code: 400
                      message: start or end date should be passed in proper format yyyy-MM-dd'T'HH:mm'Z'
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                        default: true
                      code:
                        type: integer
                        example: 400
                        default: 0
                      message:
                        type: string
                        example: start or end date should be passed in proper format yyyy-MM-dd'T'HH:mm'Z'
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/brand/1/available?startDate=2023-04-20T08:55Z&endDate=2024-07-30T08:55Z' \
            --header 'Accept: */*' \
            --header 'Authorization: Basic aWFtc2hpdmFhbms6NblahblahDM4ZjhlMzRkNWI1YTI5MWY=' \
            --header 'Cookie: _cfuvid=NJfT4sKrp52F91VHc.jjVnfGMHiYjCsRisiSMqu5.eg-1734413549869-0.0.1.1-604800000' \
            --data ''
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
