openapi: 3.1.0
info:
  title: Get Cart Promotions Config API
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/promotions/config:
    get:
      summary: Get Cart Promotions Config API
      description: This API can be used fetch the configurations of the cart promotions via promotion
        ids
      operationId: get-promotions-config-api
      parameters:
      - name: includeExpired
        in: query
        description: includes expired promotions or not
        schema:
          type: boolean
      - name: includeInactive
        in: query
        description: includes active/inactive promotions
        schema:
          type: boolean
      - name: promotionIds
        in: query
        description: Unique id assigned to any promotion created
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data:
                    - promotionId: string
                      promotionName: string
                      promotionType: POS
                      milestoneId: 0
                      groupId: 0
                      ruleId: 0
                      expiry: 0
                      description: string
                      storeCriteria:
                        type: STORE
                        values:
                        - 0
                        operator: IN
                      supplementaryCriteria:
                        loyaltyProgramId: 0
                        programType: TIER
                        partnerProgramId: 0
                      reward: string
                      maxEarningPerCustomer: 0
                      isActive: true
                      customFieldValues:
                        additionalProp1: string
                        additionalProp2: string
                        additionalProp3: string
                      promotionRestrictions:
                        additionalProp1:
                        - kpi: TRANSACTION
                          frequency: DAYS
                          minTimeBetweenRepeat: 0
                          limit: 0
                        additionalProp2:
                        - kpi: TRANSACTION
                          frequency: DAYS
                          minTimeBetweenRepeat: 0
                          limit: 0
                        additionalProp3:
                        - kpi: TRANSACTION
                          frequency: DAYS
                          minTimeBetweenRepeat: 0
                          limit: 0
                    errors:
                    - code: 0
                      message: string
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
