openapi: 3.1.0
info:
  title: Redeem Cart Promotion
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/promotions/redemptions#:
    post:
      summary: Redeem Cart Promotion
      description: This API records a customer's cart promotion redemption during a transaction.
      operationId: redeem-cart-promotion
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data:
                      orgId: 100737
                      customerIdentifierValue: '9988221100'
                      customerIdentifierType: mobile
                      customerId: 564332013
                      transactionIdentifier: txn-50
                      transactionNumber: txn-50
                      transactionDate: 1743521508000
                      amount: 1000
                      redemptions:
                      - promotionId: 67e3c1073919452f135e2da0
                        redemptionCount: 1
                        discount: '500.000000'
                        discountAppliedOnQuantity: '1.000000'
                        promotionAppliedOnQuantity: '1.000000'
                      lineItems:
                      - sku: Sku#Fuel
                        promotionId: 67e3c1073919452f135e2da0
                        earnedPromotionId: 67e63559e1c34e7d8e9348aa
                        redemptionCount: 1
                        discount: '500.000000'
                        discountAppliedOnQuantity: '1.000000'
                        promotionAppliedOnQuantity: '1.000000'
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value:
                    timestamp: 1746166870695
                    errorCode: 400
                    message: Validation Failed
                    errorDetails:
                    - CustomerIdentifierType and CustomerIdentifierValue is mandatory when customerId
                      is not specified.
              schema:
                type: object
                properties:
                  timestamp:
                    type: integer
                    example: 1746166870695
                    default: 0
                  errorCode:
                    type: integer
                    example: 400
                    default: 0
                  message:
                    type: string
                    example: Validation Failed
                  errorDetails:
                    type: array
                    items:
                      type: string
                      example: CustomerIdentifierType and CustomerIdentifierValue is mandatory when customerId
                        is not specified.
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillary\ntech.com/api_gateway/v1/promotions/redemptions'\n\
            --header 'Content-Type: application/json' \\\n--header 'X-CAP-API-AUTH-ORG-ID: 4000004' \\\
            \n--header 'Authorization: Basic bmFtYW5fZG9jOmE\nzYjRjYjgyM\nzA3MWJmYjM5OGM5ZmM2YjZlY2I2MmEy'\
            \ \\\n--data '{\n  \"customerIdentifierValue\" : \"9988221100\", \n  \"customerIdentifierType\"\
            \ : \"mobile\",\n  \"customerId\" : \"564332013\",\n  \"transactionIdentifier\" : \"txn-50\"\
            ,\n  \"transactionNumber\" : \"txn-50\",\n   \"transactionDate\":1743521508000, \n   \"amount\"\
            :1000,\n   \"lineItems\" : [\n    {\n        \"sku\":\"Sku#Fuel\", \n        \"promotionId\"\
            :\"67e3c1073919452f135e2da0\",  \n        \"earnedPromotionId\":\"67e63559e1c34e7d8e9\n348aa\"\
            , \n        \"redemptionCount\":1,\n        \"discount\":500,\n        \"discountAppliedOnQuantity\"\
            :1,\n        \"promotionAppliedOnQuantity\":1\n     }\n   ],\n   \"redemptions\" : [\n   \
            \   {\n        \"sku\":\"Sku#Fuel\", \n        \"promotionId\":\"67e3c1073919452f135e2da0\"\
            ,  \n        \"redemptionCount\":1,\n        \"discount\":500,\n        \"discountAppliedOnQuantity\"\
            :1,\n        \"promotionAppliedOnQuantity\":1\n     }\n   ]\n}'"
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
