openapi: 3.1.0
info:
  title: Perform Search (Cortex API)
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/cortex/v1/search:
    post:
      summary: Perform Search (Cortex API)
      description: ''
      operationId: search-api-cortex-api
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {}{
                        "data": {
                            "orgId": 100737,
                            "entityType": "CUSTOMER",
                            "entityDetails": [
                                {
                                    "entityId": "564647512",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine"
                                    }
                                },
                                {
                                    "entityId": "564647566",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega123"
                                    }
                                },
                                {
                                    "entityId": "564647568",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega1234"
                                    }
                                },
                                {
                                    "entityId": "564647574",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "mobile": "9988221100",
                                        "externalId": "mega12345",
                                        "email": "tom.sawyer@capillarytech.com"
                                    }
                                },
                                {
                                    "entityId": "564647589",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega123457"
                                    }
                                },
                                {
                                    "entityId": "564662467",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega123458"
                                    }
                                },
                                {
                                    "entityId": "564662468",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega123459"
                                    }
                                },
                                {
                                    "entityId": "564663537",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine",
                                        "externalId": "mega1"
                                    }
                                },
                                {
                                    "entityId": "564663541",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine1",
                                        "externalId": "megaa"
                                    }
                                },
                                {
                                    "entityId": "564663557",
                                    "entityData": {
                                        "firstName": "dave",
                                        "lastName": "mustaine1",
                                        "externalId": "megaa1"
                                    }
                                }
                            ]
                        },
                        "errors": []
                    }
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: {}
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'eu.api.capillarytech.com/api_gateway/cortex/v1/search' \
            --header 'Content-Type: application/json' \
            --data '{
                "entityType": "CUSTOMER",

                "searchConditions": [
                    {
                        "fieldId": "search_prefix",
                        "operator": "STARTS_WITH",
                        "values": [
                            "Dave"
                        ]
                    }
                ]

            } '
          name: Using starts_with
        - language: curl
          code: |-
            curl --location 'eu.api.capillarytech.com/api_gateway/cortex/v1/search' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic bmVlcmFqLmRvYzpiNGFmO0MDA5Y2IwMzZhNGNjZGMzMzQzMWVmOWFjOQ==' \
            --header 'Cookie: _cfuvid=712eXDq0ppxlT168Xp.8agHB9AIF3dm1OHgmh0Qi_x0-1747981082674-0.0.1.1-604800000' \
            --data '{
                "entityType": "CUSTOMER",

                "searchConditions": [
                    {
                        "fieldId": "search_prefix",
                        "operator": "STARTS_WITH",
                        "values": [
                            "Dave"
                        ]
                    }
                ],
                "limit": 10,
                "offset":3

            } '
          name: with limit and offset
        - language: curl
          code: |-
            curl --location 'eu.api.capillarytech.com/api_gateway/cortex/v1/search' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic bmVlcmFqLmRvYzpiNGFmO0MDA5Y2IwMzZhNGNjZGMzMzQzMWVmOWFjOQ==' \
            --header 'Cookie: _cfuvid=712eXDq0ppxlT168Xp.8agHB9AIF3dm1OHgmh0Qi_x0-1747981082674-0.0.1.1-604800000' \
            --data '{
                "entityType": "CUSTOMER",

                "searchConditions": [
                    {
                        "fieldId": "firstName",
                        "operator": "EQUALS,
                        "values": [
                            "Dave"
                        ]
                    }
                ],
                "limit": 10,
                "offset":3

            } '
          name: using Equals
        - language: curl
          code: |-
            curl --location 'eu.api.capillarytech.com/api_gateway/cortex/v1/search' \
            --header 'Content-Type: application/json' \
            --data '{
                "entityType": "CUSTOMER",

                "searchConditions": [
                    {
                        "fieldId": "createdAt",
                        "operator": "RANGE",
                        "values": [
                            1625097600, 1625184000
                        ]
                    }
                ]

            } '
          name: with range
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
