openapi: 3.1.0
info:
  title: Get badges org meta
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/orgMeta:
    get:
      summary: Get badges org meta
      description: ''
      operationId: get-badges-org-meta
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data:
                      id: string
                      orgId: orgId
                      tags:
                      - key: Type
                        dataType: string
                        description: Type of badge(Exclusive,Regular)
                        mandatory: false
                      - key: Priority
                        dataType: integer
                        description: Priority of the badge
                        mandatory: false
                      createdOn: 1697636680.484
                      createdBy: 75097962
                      lastUpdatedOn: 1699459111.747
                      lastUpdatedBy: 75097962
                    errors: null
                    warnings: null
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
